### ISSUE TITLE
Develop base32 RID support for ermrest and an upgrade procedure

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#171]
@karlcz commented on [Fri Oct 13 2017](https://github.com/informatics-isi-edu/division/issues/137)

- [x] Determine how to revise the RID column type for a balance between efficiency, code simplicity, and correctness
- [x] Get this working in the stateful-model branch for new catalogs and full test suite run
- [x] Come up with an upgrade procedure to convert an existing stateful-model catalog to the new format in place
- [x] Extract an equivalent, external procedure to upgrade a legacy (master) catalog that has already done the ermrest-rid-upgrade procedure to add the system columns with int8 RID.

**Comment by karlcz** [comment]
I did a quick and dirty conversion of the ermrest_rid domain into `text` base type and the whole test suite runs an essentially the same time as before with `int8`...  so, there doesn't seem to be a need to do anything more complicated.

**Comment by karlcz** [comment]
I've got an ugly conversion script now which works for a test catalog I have.  It might be time for someone to test it on their own test catalog snapshots to see if we need anything more complex than this.  I'm debating whether to enable this conversion during `ermrest-deploy` or to leave it as a manual step that a DBA must run if they need to upgrade a catalog.

The way to test it would be to create a copy of a catalog DB, e.g. via restoring a dump, and then running this command on it as the ermrest user:

    psql --single-transaction mytestdb < ermrest/sql/ermrest_rid_preupgrade.sql

where this is given relative to a checked out copy of the ermrest/stateful-model repo branch.

If this runs to completion and commits rather than raising an error, then a subsequent `ermrest-deploy` from this same branch *should* be able to fix it up and make it a working catalog (assuming `mytestdb` is present in `ermrest.simple_registry`.  The preupgrade script drops dependent views and a lot of `_ermrest` schema stuff that might be present and conflicting with the conversion of `ermrest_rid` from `int8` to `text` storage. The idempotent deployment routines should then fix it up again...

@robes

**Comment by robes** [comment]
So this is expecting that we are using the history tables not just the system columns? FB is not using the history branch just the system columns at this time.

```
ERROR:  relation "_ermrest_history.known_types" does not exist
LINE 1: UPDATE _ermrest_history.known_types
               ^
QUERY:  UPDATE _ermrest_history.known_types
  SET rowdata = jsonb_set(rowdata, '{domain_element_type_rid}'::text[], to_jsonb((SELECT "RID" FROM _ermrest.known_types WHERE type_name = 'text')))
  WHERE rowdata->>'type_name' = 'ermrest_rid'
CONTEXT:  PL/pgSQL function inline_code_block line 360 at SQL statement
```

**Comment by karlcz** [comment]
No that seems like a bug... the rest of the code for `_ermrest_history` was all inside a test for that schema being present, but that last fixup at the end is missing a similar test...

**Comment by karlcz** [comment]
I pushed a small patch to address that. @robes

**Comment by robes** [comment]
@karlcz seems to have worked.

```
NOTICE:  Restoring fkey constraint sample_replicate_group_fkey on table isa . sample
NOTICE:  Completed conversion of int8 ermrest_rid to text ermrest_rid.
DO
```

We were about to push out to production and then start letting users to "self-curation". Think this is safe enough to do on our production catalog before pushing out...?

cc: @bugacov

**Comment by robes** [comment]
Converted test catalog is here https://dev.facebase.org/data/recordset/#5/isa:dataset

**Comment by karlcz** [comment]
Well, you need to review the damage it caused.  I.e. it may have removed SQL view definitions that depended on the old RID column, in which case you need to re-create the views based on the revised RID column.  And if you have any UX where RIDs are actually displayed or cooked into other mustache templates, you might need to review how that is working...

**Comment by robes** [comment]
As we discussed elsewhere...

I messed up. I didn't run the ermrest-deploy part of the procedure and didn't notice that the model/data change functions were not there. ermrest-deploy from master did not fix it.

We restored the FB db from backups.
